trigger:
  branches:
    include:
    - main  # Adjust if your main branch has a different name

jobs:
- job: SyncJob
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - script: |
      git config --global user.email "r0768810@student.thomasmore.be"
      git config --global user.name "Hodor-Fergus"
      git remote add azure https://dev.azure.com/FergusEssoKetchaAssam/_git/Eco%20PLay
      git push azure main --force
    displayName: 'Push changes to Azure Repos'
    env:
      AZURE_DEVOPS_EXT_PAT: $(AzureDevOpsPAT)  # Uses the secret PAT for authentication
